name: Node Build
run-name: Build Node.js Application
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Verificar Node.js instalado
        run: node -v

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: npm ci

      - name: Compilar el aplicativo
        working-directory: ./calculadora
        run: npm run build


